package net.marcusdevcode.zexpend.entities.bulk;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import net.marcusdevcode.zexpend.ZexpendMod;

import java.io.InputStreamReader;
import java.io.Reader;
import java.nio.charset.StandardCharsets;

/**
 * Loads the {@code assets/zexpendmod/bulk_skins/*.json} manifests (generated by scanning
 * {@code textures/entity/{zombie,husk,drowned}/} for the numbered skin files they contain).
 * Read once at class-load time as a plain classpath resource, so it works identically in dev
 * and in a packaged jar without needing a registered resource-reload listener.
 */
public final class BulkSkinManifest {
    public static final int[] ZOMBIE = load("zombie");
    public static final int[] HUSK = load("husk");
    public static final int[] DROWNED = load("drowned");

    private BulkSkinManifest() {
    }

    private static int[] load(String category) {
        String path = "/assets/" + ZexpendMod.MOD_ID + "/bulk_skins/" + category + ".json";
        try (Reader reader = new InputStreamReader(BulkSkinManifest.class.getResourceAsStream(path), StandardCharsets.UTF_8)) {
            JsonObject json = JsonParser.parseReader(reader).getAsJsonObject();
            JsonArray indices = json.getAsJsonArray("indices");
            int[] result = new int[indices.size()];
            for (int i = 0; i < indices.size(); i++) {
                result[i] = indices.get(i).getAsInt();
            }
            return result;
        } catch (Exception e) {
            ZexpendMod.LOGGER.error("Failed to load bulk skin manifest for '{}'", category, e);
            return new int[0];
        }
    }
}
